# 新界梯子每日自动签到
name: 新界每日签到

on:
  workflow_dispatch:
  schedule:
    - cron: '7 0 * * *'

permissions:
  contents: read

jobs:
  sign-in:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v4
    - name: 设置 Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 执行签到
      env:
         USERNAME: ${{ secrets.USERNAME }}
         PASSWORD: ${{ secrets.PASSWORD }}
         USERNAME8344: ${{ secrets.USERNAME8344 }}
         PASSWORD8344: ${{ secrets.PASSWORD8344 }}
         USERNAME1325: ${{ secrets.USERNAME1325 }}
         PASSWORD1325: ${{ secrets.PASSWORD1325 }}
         CHECKIN_TYPE: "1"
      run: |
        python checkin.py
